---
- stat: path="~/.zshrc"
  register: zshrc_file

- stat: path="~/.bashrc"
  register: bashrc_file

- name: "AUTOJUMP | Configure autojump | zshrc"
  lineinfile:
    path: ~/.zshrc
    insertafter: EOF
    state: present
    line: ". /usr/share/autojump/autojump.sh"
  when: 'zshrc_file.stat.exists'

- name: "AUTOJUMP | Configure autojump | bashrc"
  lineinfile:
    path: ~/.bashrc
    insertafter: EOF
    state: present
    line: ". /usr/share/autojump/autojump.sh"
  when: 'bashrc_file.stat.exists'